# Generated by Django 3.0.6 on 2020-05-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computersimage',
            old_name='game',
            new_name='computers',
        ),
        migrations.RemoveField(
            model_name='computers',
            name='category',
        ),
        migrations.DeleteModel(
            name='ComputersCategory',
        ),
    ]
