# Generated by Django 3.0.6 on 2020-05-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20200511_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computersimage',
            old_name='computers',
            new_name='computers_id',
        ),
    ]
