# Generated by Django 3.0.6 on 2020-05-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computers_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_start', models.DateTimeField()),
            ],
        ),
    ]
