# Generated by Django 3.0.6 on 2020-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersimage',
            name='image2',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
