# Generated by Django 3.0.6 on 2020-05-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20200511_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computersimage',
            old_name='computers_id',
            new_name='computers',
        ),
    ]
