# Generated by Django 3.0.6 on 2020-05-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0002_computers_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=999)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('on_sale', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GamesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GamesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GamesCategory'),
        ),
        migrations.AddField(
            model_name='games',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.Computers'),
        ),
    ]
