# Generated by Django 3.0.6 on 2020-05-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesimage',
            old_name='games',
            new_name='games_id',
        ),
    ]
