# Generated by Django 3.0.6 on 2020-05-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
        ('games', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='console',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='computers.Computers'),
            preserve_default=False,
        ),
    ]
