# Generated by Django 3.0.6 on 2020-05-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200511_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesimage',
            old_name='games_id',
            new_name='game_id',
        ),
    ]
