# Generated by Django 3.0.6 on 2020-05-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_games_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
