# Generated by Django 3.0.6 on 2020-05-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200511_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesimage',
            old_name='game_id',
            new_name='games',
        ),
    ]
