# Generated by Django 3.0.6 on 2020-05-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='BuyerInfo',
        ),
    ]
