# Generated by Django 3.0.6 on 2020-05-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_buyerinfo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinfo',
            name='product',
        ),
    ]
