# Generated by Django 3.0.6 on 2020-05-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_buyerinfo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='buyer_id',
        ),
    ]
